name: Build project and validate formatting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2
    - name: Build project
      run: mvn test -B
    - name: Validate formatting
      run: mvn validate formatter:validate
